name: AI-Guard

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch:

jobs:
  guard:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 src tests

      - name: Static type check (mypy)
        run: mypy src

      - name: Security scan (bandit)
        run: bandit -r src -c .bandit

      - name: Run tests with coverage
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Generate speculative tests for changed code
        run: python -m src.ai_guard.generators.testgen --event "$GITHUB_EVENT_PATH"

      - name: Re-run tests with speculative tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Enforce quality gates
        run: python -m src.ai_guard.analyzer --min-cov 80
